Add first ip address to service in BonjourMDNSManager
pdgendt/mDNSWrapper pull request #3
Opened 2023-04-12 12:58 UTC by michieldwitte

Add first IP address to service if present

2023-04-12 14:25 UTC, DarthBo commented on src/BonjourMDNSManager.cpp
> +                    std::string hostip = inet_ntoa(**(struct in_addr **) host_struct->h_addr_list);
Is blindly picking the first address safe?

I'm not sure I trust the thread safety of `inet_ntoa` (uses an internal static char buffer). Consider using `inet_ntop` instead.

2023-04-13 08:11 UTC, pdgendt commented on src/BonjourMDNSManager.cpp
> +                hostent* host_struct = gethostbyname(hosttarget);
Quoting the manual:
> The gethostbyname*(), gethostbyaddr*(), herror(), and hstrerror()
       functions are obsolete.  Applications should use [getaddrinfo(3)](https://man7.org/linux/man-pages/man3/getaddrinfo.3.html),
       [getnameinfo(3)](https://man7.org/linux/man-pages/man3/getnameinfo.3.html), and [gai_strerror(3)](https://man7.org/linux/man-pages/man3/gai_strerror.3.html) instead.

2023-04-13 09:14 UTC, pdgendt requested changes

2023-04-13 09:14 UTC, pdgendt commented on src/BonjourMDNSManager.cpp
> +                    }
`result` is a linked list, do you only want to check the first element?

Also missing `freeaddrinfo(result);`

2023-04-13 09:32 UTC, pdgendt approved these changes

2023-04-13 09:33 UTC, merged